#!/usr/bin/env bash
set -e

cd "$(dirname "$(dirname "$0")")"

root=$(pwd)
# items=$(find "$root/packages" \( -name node_modules -or -name package-lock.json \))
items=$(find "$root/packages" -name node_modules)

for item in $items
do
  rm -rf "$item"
done
rm -rf "$root/node_modules"
npm ci
# npx lerna bootsrap
# npx lerna link
