#!/usr/bin/env bash
set -e

root="$(dirname "$(dirname "$0")")"
cd "$root"

echo "lerna clean --yes"
npx lerna clean --yes || :
echo "rm -rf node_modules package-lock.json"
if [ -d "$HOME/.Trash" ]; then
  mv "$root/node_modules" "$HOME/.Trash/node_modules"
fi
rm -rf "$root/node_modules" "$root/package-lock.json"
items=$(find "$root/packages" \( -name dist -or -name package-lock.json \))

for item in $items
do
  echo "rm -rf $item"
  rm -rf "$item"
done
