#!/usr/bin/env bash
set -e

# pre-release checks
npm run build
npm run lint
npm test

# release
npx release-it
tag=$(git describe)
npm version $tag --workspaces --no-git-tag-version
npm publish --workspaces
