#!/usr/bin/env bash
set -e

# checks
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" != "main" ]; then
  echo "Can only release on branch 'main'"
  exit 1
fi

# pre-release checks
npm run build
npm run lint
npm test

# read version
echo ""
echo -n "Version: "
read -r tag
echo ""

# create git tag
git tag "v$tag" -m "Release v$tag"
git push origin "v$tag"

# publish to npm
npm version "$tag" --workspaces --no-git-tag-version --include-workspace-root
git add .
git commit -m "Release v$tag"
git push
npm publish --workspaces

# create a github release
gh release create --draft
