#!/usr/bin/env node
const log = require('signale');
const pkg = require('../package.json');
const exec = require('./helpers/exec');

const updateDependencies = async (object = {}, flags = []) => {
  const keys = Object.keys(object);
  if (!keys.length) return;
  const string = keys.map((key) => `${key}@latest`).join(' ');
  const command = `npm install ${flags.join(' ')} ${string}`;
  log.info(`Running ${command}`);
  await exec(command);
};

const getDependenciesCmd = async () => {
  await updateDependencies(pkg.dependencies);
  log.info('Installing dependencies');
};

const getDevDependenciesCmd = async () => {
  await updateDependencies(pkg.devDependencies, ['--save-dev']);
  log.info('Installing dev dependencies');
};

const main = async () => {
  await getDependenciesCmd();
  await getDevDependenciesCmd();
};

main()
  .then(() => {
    log.success('Dependencies updated');
  })
  .catch((error) => {
    log.error(error);
    process.exit(1);
  });
